package pgn2rdf.chess;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author vroddon
 */
public class ChessECOManager {
    
    public static Map<String, String> mapa = init();
    
    public static String getName(String eco)
    {
        String name="";
        
        name = mapa.get(eco);
        return name;
    }
    
    public static Map<String, String> init()
    {
        Map<String, String> mapa = new HashMap();
mapa.put("A00","Uncommon Opening");
mapa.put("A01","Nimzovich-Larsen Attack");
mapa.put("A02","Bird's Opening");
mapa.put("A03","Bird's Opening");
mapa.put("A04","Reti Opening");
mapa.put("A05","Reti Opening");
mapa.put("A06","Reti Opening");
mapa.put("A07","King's Indian Attack");
mapa.put("A08","King's Indian Attack");
mapa.put("A09","Reti Opening");
mapa.put("A10","English");
mapa.put("A11","English, Caro-Kann Defensive System");
mapa.put("A12","English with b3");
mapa.put("A13","English");
mapa.put("A14","English");
mapa.put("A15","English");
mapa.put("A16","English");
mapa.put("A17","English");
mapa.put("A18","English, Mikenas-Carls");
mapa.put("A19","English, Mikenas-Carls, Sicilian Variation");
mapa.put("A20","English");
mapa.put("A21","English");
mapa.put("A22","English");
mapa.put("A23","English, Bremen System, Keres Variation");
mapa.put("A24","English, Bremen System with ...g6");
mapa.put("A25","English");
mapa.put("A26","English");
mapa.put("A27","English, Three Knights System");
mapa.put("A28","English");
mapa.put("A29","English, Four Knights, Kingside Fianchetto");
mapa.put("A30","English, Symmetrical");
mapa.put("A31","English, Symmetrical, Benoni Formation");
mapa.put("A32","English, Symmetrical Variation");
mapa.put("A33","English, Symmetrical");
mapa.put("A34","English, Symmetrical");
mapa.put("A35","English, Symmetrical");
mapa.put("A36","English");
mapa.put("A37","English, Symmetrical");
mapa.put("A38","English, Symmetrical");
mapa.put("A39","English, Symmetrical, Main line with d4");
mapa.put("A40","Queen's Pawn Game");
mapa.put("A41","Queen's Pawn Game (with ...d6)");
mapa.put("A42","Modern Defense, Averbakh System");
mapa.put("A43","Old Benoni");
mapa.put("A44","Old Benoni Defense");
mapa.put("A45","Queen's Pawn Game");
mapa.put("A46","Queen's Pawn Game");
mapa.put("A47","Queen's Indian");
mapa.put("A48","King's Indian");
mapa.put("A49","King's Indian, Fianchetto without c4");
mapa.put("A50","Queen's Pawn Game");
mapa.put("A51","Budapest Gambit");
mapa.put("A52","Budapest Gambit");
mapa.put("A53","Old Indian");
mapa.put("A54","Old Indian, Ukrainian Variation, 4.Nf3");
mapa.put("A55","Old Indian, Main line");
mapa.put("A56","Benoni Defense");
mapa.put("A57","Benko Gambit");
mapa.put("A58","Benko Gambit");
mapa.put("A59","Benko Gambit");
mapa.put("A60","Benoni Defense");
mapa.put("A61","Benoni");
mapa.put("A62","Benoni, Fianchetto Variation");
mapa.put("A63","Benoni, Fianchetto, 9...Nbd7");
mapa.put("A64","Benoni, Fianchetto, 11...Re8");
mapa.put("A65","Benoni, 6.e4");
mapa.put("A66","Benoni");
mapa.put("A67","Benoni, Taimanov Variation");
mapa.put("A68","Benoni, Four Pawns Attack");
mapa.put("A69","Benoni, Four Pawns Attack, Main line");
mapa.put("A70","Benoni, Classical with 7.Nf3");
mapa.put("A71","Benoni, Classical, 8.Bg5");
mapa.put("A72","Benoni, Classical without 9.O-O");
mapa.put("A73","Benoni, Classical, 9.O-O");
mapa.put("A74","Benoni, Classical, 9...a6, 10.a4");
mapa.put("A75","Benoni, Classical with ...a6 and 10...Bg4");
mapa.put("A76","Benoni, Classical, 9...Re8");
mapa.put("A77","Benoni, Classical, 9...Re8, 10.Nd2");
mapa.put("A78","Benoni, Classical with ...Re8 and ...Na6");
mapa.put("A79","Benoni, Classical, 11.f3");
mapa.put("A80","Dutch");
mapa.put("A81","Dutch");
mapa.put("A82","Dutch, Staunton Gambit");
mapa.put("A83","Dutch, Staunton Gambit");
mapa.put("A84","Dutch");
mapa.put("A85","Dutch, with c4 & Nc3");
mapa.put("A86","Dutch");
mapa.put("A87","Dutch, Leningrad, Main Variation");
mapa.put("A88","Dutch, Leningrad, Main Variation with c6");
mapa.put("A89","Dutch, Leningrad, Main Variation with Nc6");
mapa.put("A90","Dutch");
mapa.put("A91","Dutch Defense");
mapa.put("A92","Dutch");
mapa.put("A93","Dutch, Stonewall, Botvinnik Variation");
mapa.put("A94","Dutch, Stonewall with Ba3");
mapa.put("A95","Dutch, Stonewall");
mapa.put("A96","Dutch, Classical Variation");
mapa.put("A97","Dutch, Ilyin-Genevsky");
mapa.put("A98","Dutch, Ilyin-Genevsky Variation with Qc2");
mapa.put("A99","Dutch, Ilyin-Genevsky Variation with b3");
mapa.put("B00","Uncommon King's Pawn Opening");
mapa.put("B01","Scandinavian");
mapa.put("B02","Alekhine's Defense");
mapa.put("B03","Alekhine's Defense");
mapa.put("B04","Alekhine's Defense, Modern");
mapa.put("B05","Alekhine's Defense, Modern");
mapa.put("B06","Robatsch");
mapa.put("B07","Pirc");
mapa.put("B08","Pirc, Classical");
mapa.put("B09","Pirc, Austrian Attack");
mapa.put("B10","Caro-Kann");
mapa.put("B11","Caro-Kann, Two Knights, 3...Bg4");
mapa.put("B12","Caro-Kann Defense");
mapa.put("B13","Caro-Kann, Exchange");
mapa.put("B14","Caro-Kann, Panov-Botvinnik Attack");
mapa.put("B15","Caro-Kann");
mapa.put("B16","Caro-Kann, Bronstein-Larsen Variation");
mapa.put("B17","Caro-Kann, Steinitz Variation");
mapa.put("B18","Caro-Kann, Classical");
mapa.put("B19","Caro-Kann, Classical");
mapa.put("B20","Sicilian");
mapa.put("B21","Sicilian, 2.f4 and 2.d4");
mapa.put("B22","Sicilian, Alapin");
mapa.put("B23","Sicilian, Closed");
mapa.put("B24","Sicilian, Closed");
mapa.put("B25","Sicilian, Closed");
mapa.put("B26","Sicilian, Closed, 6.Be3");
mapa.put("B27","Sicilian");
mapa.put("B28","Sicilian, O'Kelly Variation");
mapa.put("B29","Sicilian, Nimzovich-Rubinstein");
mapa.put("B30","Sicilian");
mapa.put("B31","Sicilian, Rossolimo Variation");
mapa.put("B32","Sicilian");
mapa.put("B33","Sicilian");
mapa.put("B34","Sicilian, Accelerated Fianchetto");
mapa.put("B35","Sicilian, Accelerated Fianchetto, Modern Variation with Bc4");
mapa.put("B36","Sicilian, Accelerated Fianchetto");
mapa.put("B37","Sicilian, Accelerated Fianchetto");
mapa.put("B38","Sicilian, Accelerated Fianchetto, Maroczy Bind, 6.Be3");
mapa.put("B39","Sicilian, Accelerated Fianchetto, Breyer Variation");
mapa.put("B40","Sicilian");
mapa.put("B41","Sicilian, Kan");
mapa.put("B42","Sicilian, Kan");
mapa.put("B43","Sicilian, Kan, 5.Nc3");
mapa.put("B44","Sicilian");
mapa.put("B45","Sicilian, Taimanov");
mapa.put("B46","Sicilian, Taimanov Variation");
mapa.put("B47","Sicilian, Taimanov (Bastrikov) Variation");
mapa.put("B48","Sicilian, Taimanov Variation");
mapa.put("B49","Sicilian, Taimanov Variation");
mapa.put("B50","Sicilian");
mapa.put("B51","Sicilian, Canal-Sokolsky (Rossolimo) Attack");
mapa.put("B52","Sicilian, Canal-Sokolsky (Rossolimo) Attack");
mapa.put("B53","Sicilian");
mapa.put("B54","Sicilian");
mapa.put("B55","Sicilian, Prins Variation, Venice Attack");
mapa.put("B56","Sicilian");
mapa.put("B57","Sicilian");
mapa.put("B58","Sicilian");
mapa.put("B59","Sicilian, Boleslavsky Variation, 7.Nb3");
mapa.put("B60","Sicilian, Richter-Rauzer");
mapa.put("B61","Sicilian, Richter-Rauzer, Larsen Variation, 7.Qd2");
mapa.put("B62","Sicilian, Richter-Rauzer");
mapa.put("B63","Sicilian, Richter-Rauzer Attack");
mapa.put("B64","Sicilian, Richter-Rauzer Attack");
mapa.put("B65","Sicilian, Richter-Rauzer Attack, 7...Be7 Defense, 9...Nxd4");
mapa.put("B66","Sicilian, Richter-Rauzer Attack, 7...a6");
mapa.put("B67","Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 8...Bd7");
mapa.put("B68","Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 9...Be7");
mapa.put("B69","Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 11.Bxf6");
mapa.put("B70","Sicilian, Dragon Variation");
mapa.put("B71","Sicilian, Dragon, Levenfish Variation");
mapa.put("B72","Sicilian, Dragon");
mapa.put("B73","Sicilian, Dragon, Classical");
mapa.put("B74","Sicilian, Dragon, Classical");
mapa.put("B75","Sicilian, Dragon, Yugoslav Attack");
mapa.put("B76","Sicilian, Dragon, Yugoslav Attack");
mapa.put("B77","Sicilian, Dragon, Yugoslav Attack");
mapa.put("B78","Sicilian, Dragon, Yugoslav Attack, 10.castle long");
mapa.put("B79","Sicilian, Dragon, Yugoslav Attack, 12.h4");
mapa.put("B80","Sicilian, Scheveningen");
mapa.put("B81","Sicilian, Scheveningen, Keres Attack");
mapa.put("B82","Sicilian, Scheveningen");
mapa.put("B83","Sicilian");
mapa.put("B84","Sicilian, Scheveningen");
mapa.put("B85","Sicilian, Scheveningen, Classical");
mapa.put("B86","Sicilian, Fischer-Sozin Attack");
mapa.put("B87","Sicilian, Fischer-Sozin with ...a6 and ...b5");
mapa.put("B88","Sicilian, Fischer-Sozin Attack");
mapa.put("B89","Sicilian");
mapa.put("B90","Sicilian, Najdorf");
mapa.put("B91","Sicilian, Najdorf, Zagreb (Fianchetto) Variation");
mapa.put("B92","Sicilian, Najdorf, Opocensky Variation");
mapa.put("B93","Sicilian, Najdorf, 6.f4");
mapa.put("B94","Sicilian, Najdorf");
mapa.put("B95","Sicilian, Najdorf, 6...e6");
mapa.put("B96","Sicilian, Najdorf");
mapa.put("B97","Sicilian, Najdorf");
mapa.put("B98","Sicilian, Najdorf");
mapa.put("B99","Sicilian, Najdorf, 7...Be7 Main line");
mapa.put("C00","French Defense");
mapa.put("C01","French, Exchange");
mapa.put("C02","French, Advance");
mapa.put("C03","French, Tarrasch");
mapa.put("C04","French, Tarrasch, Guimard Main line");
mapa.put("C05","French, Tarrasch");
mapa.put("C06","French, Tarrasch");
mapa.put("C07","French, Tarrasch");
mapa.put("C08","French, Tarrasch, Open, 4.ed ed");
mapa.put("C09","French, Tarrasch, Open Variation, Main line");
mapa.put("C10","French");
mapa.put("C11","French");
mapa.put("C12","French, McCutcheon");
mapa.put("C13","French");
mapa.put("C14","French, Classical");
mapa.put("C15","French, Winawer");
mapa.put("C16","French, Winawer");
mapa.put("C17","French, Winawer, Advance");
mapa.put("C18","French, Winawer");
mapa.put("C19","French, Winawer, Advance");
mapa.put("C20","King's Pawn Game");
mapa.put("C21","Center Game");
mapa.put("C22","Center Game");
mapa.put("C23","Bishop's Opening");
mapa.put("C24","Bishop's Opening");
mapa.put("C25","Vienna");
mapa.put("C26","Vienna");
mapa.put("C27","Vienna Game");
mapa.put("C28","Vienna Game");
mapa.put("C29","Vienna Gambit");
mapa.put("C30","King's Gambit Declined");
mapa.put("C31","King's Gambit Declined, Falkbeer Counter Gambit");
mapa.put("C32","King's Gambit Declined, Falkbeer Counter Gambit");
mapa.put("C33","King's Gambit Accepted");
mapa.put("C34","King's Gambit Accepted");
mapa.put("C35","King's Gambit Accepted, Cunningham");
mapa.put("C36","King's Gambit Accepted, Abbazia Defense");
mapa.put("C37","King's Gambit Accepted");
mapa.put("C38","King's Gambit Accepted");
mapa.put("C39","King's Gambit Accepted");
mapa.put("C40","King's Knight Opening");
mapa.put("C41","Philidor Defense");
mapa.put("C42","Petrov Defense");
mapa.put("C43","Petrov, Modern Attack");
mapa.put("C44","King's Pawn Game");
mapa.put("C45","Scotch Game");
mapa.put("C46","Three Knights");
mapa.put("C47","Four Knights");
mapa.put("C48","Four Knights");
mapa.put("C49","Four Knights");
mapa.put("C50","Giuoco Piano");
mapa.put("C51","Evans Gambit");
mapa.put("C52","Evans Gambit");
mapa.put("C53","Giuoco Piano");
mapa.put("C54","Giuoco Piano");
mapa.put("C55","Two Knights Defense");
mapa.put("C56","Two Knights");
mapa.put("C57","Two Knights");
mapa.put("C58","Two Knights");
mapa.put("C59","Two Knights");
mapa.put("C60","Ruy Lopez");
mapa.put("C61","Ruy Lopez, Bird's Defense");
mapa.put("C62","Ruy Lopez, Old Steinitz Defense");
mapa.put("C63","Ruy Lopez, Schliemann Defense");
mapa.put("C64","Ruy Lopez, Classical");
mapa.put("C65","Ruy Lopez, Berlin Defense");
mapa.put("C66","Ruy Lopez");
mapa.put("C67","Ruy Lopez");
mapa.put("C68","Ruy Lopez, Exchange");
mapa.put("C69","Ruy Lopez, Exchange, Gligoric Variation, 6.d4");
mapa.put("C70","Ruy Lopez");
mapa.put("C71","Ruy Lopez");
mapa.put("C72","Ruy Lopez, Modern Steinitz Defense, 5.O-O");
mapa.put("C73","Ruy Lopez, Modern Steinitz Defense");
mapa.put("C74","Ruy Lopez, Modern Steinitz Defense");
mapa.put("C75","Ruy Lopez, Modern Steinitz Defense");
mapa.put("C76","Ruy Lopez, Modern Steinitz Defense, Fianchetto Variation");
mapa.put("C77","Ruy Lopez");
mapa.put("C78","Ruy Lopez");
mapa.put("C79","Ruy Lopez, Steinitz Defense Deferred");
mapa.put("C80","Ruy Lopez, Open");
mapa.put("C81","Ruy Lopez, Open, Howell Attack");
mapa.put("C82","Ruy Lopez, Open");
mapa.put("C83","Ruy Lopez, Open");
mapa.put("C84","Ruy Lopez, Closed");
mapa.put("C85","Ruy Lopez, Exchange Variation Doubly Deferred (DERLD)");
mapa.put("C86","Ruy Lopez, Worrall Attack");
mapa.put("C87","Ruy Lopez");
mapa.put("C88","Ruy Lopez");
mapa.put("C89","Ruy Lopez, Marshall");
mapa.put("C90","Ruy Lopez, Closed");
mapa.put("C91","Ruy Lopez, Closed");
mapa.put("C92","Ruy Lopez, Closed");
mapa.put("C93","Ruy Lopez, Closed, Smyslov Defense");
mapa.put("C94","Ruy Lopez, Closed, Breyer Defense");
mapa.put("C95","Ruy Lopez, Closed, Breyer");
mapa.put("C96","Ruy Lopez, Closed");
mapa.put("C97","Ruy Lopez, Closed, Chigorin");
mapa.put("C98","Ruy Lopez, Closed, Chigorin");
mapa.put("C99","Ruy Lopez, Closed, Chigorin, 12...cd");
mapa.put("D00","Queen's Pawn Game");
mapa.put("D01","Richter-Veresov Attack");
mapa.put("D02","Queen's Pawn Game");
mapa.put("D03","Torre Attack (Tartakower Variation)");
mapa.put("D04","Queen's Pawn Game");
mapa.put("D05","Queen's Pawn Game");
mapa.put("D06","Queen's Gambit Declined");
mapa.put("D07","Queen's Gambit Declined, Chigorin Defense");
mapa.put("D08","Queen's Gambit Declined, Albin Counter Gambit");
mapa.put("D09","Queen's Gambit Declined, Albin Counter Gambit, 5.g3");
mapa.put("D10","Queen's Gambit Declined Slav");
mapa.put("D11","Queen's Gambit Declined Slav");
mapa.put("D12","Queen's Gambit Declined Slav");
mapa.put("D13","Queen's Gambit Declined Slav, Exchange Variation");
mapa.put("D14","Queen's Gambit Declined Slav, Exchange Variation");
mapa.put("D15","Queen's Gambit Declined Slav");
mapa.put("D16","Queen's Gambit Declined Slav");
mapa.put("D17","Queen's Gambit Declined Slav");
mapa.put("D18","Queen's Gambit Declined Slav, Dutch");
mapa.put("D19","Queen's Gambit Declined Slav, Dutch");
mapa.put("D20","Queen's Gambit Accepted");
mapa.put("D21","Queen's Gambit Accepted");
mapa.put("D22","Queen's Gambit Accepted");
mapa.put("D23","Queen's Gambit Accepted");
mapa.put("D24","Queen's Gambit Accepted");
mapa.put("D25","Queen's Gambit Accepted");
mapa.put("D26","Queen's Gambit Accepted");
mapa.put("D27","Queen's Gambit Accepted, Classical");
mapa.put("D28","Queen's Gambit Accepted, Classical");
mapa.put("D29","Queen's Gambit Accepted, Classical");
mapa.put("D30","Queen's Gambit Declined");
mapa.put("D31","Queen's Gambit Declined");
mapa.put("D32","Queen's Gambit Declined, Tarrasch");
mapa.put("D33","Queen's Gambit Declined, Tarrasch");
mapa.put("D34","Queen's Gambit Declined, Tarrasch");
mapa.put("D35","Queen's Gambit Declined");
mapa.put("D36","Queen's Gambit Declined, Exchange, Positional line, 6.Qc2");
mapa.put("D37","Queen's Gambit Declined");
mapa.put("D38","Queen's Gambit Declined, Ragozin Variation");
mapa.put("D39","Queen's Gambit Declined, Ragozin, Vienna Variation");
mapa.put("D40","Queen's Gambit Declined, Semi-Tarrasch");
mapa.put("D41","Queen's Gambit Declined, Semi-Tarrasch");
mapa.put("D42","Queen's Gambit Declined, Semi-Tarrasch, 7.Bd3");
mapa.put("D43","Queen's Gambit Declined Semi-Slav");
mapa.put("D44","Queen's Gambit Declined Semi-Slav");
mapa.put("D45","Queen's Gambit Declined Semi-Slav");
mapa.put("D46","Queen's Gambit Declined Semi-Slav");
mapa.put("D47","Queen's Gambit Declined Semi-Slav");
mapa.put("D48","Queen's Gambit Declined Semi-Slav, Meran");
mapa.put("D49","Queen's Gambit Declined Semi-Slav, Meran");
mapa.put("D50","Queen's Gambit Declined");
mapa.put("D51","Queen's Gambit Declined");
mapa.put("D52","Queen's Gambit Declined");
mapa.put("D53","Queen's Gambit Declined");
mapa.put("D54","Queen's Gambit Declined, Anti-Neo-Orthodox Variation");
mapa.put("D55","Queen's Gambit Declined");
mapa.put("D56","Queen's Gambit Declined");
mapa.put("D57","Queen's Gambit Declined, Lasker Defense");
mapa.put("D58","Queen's Gambit Declined, Tartakower (Makagonov-Bondarevsky) System");
mapa.put("D59","Queen's Gambit Declined, Tartakower");
mapa.put("D60","Queen's Gambit Declined, Orthodox Defense");
mapa.put("D61","Queen's Gambit Declined, Orthodox, Rubinstein Attack");
mapa.put("D62","Queen's Gambit Declined, Orthodox, Rubinstein Attack");
mapa.put("D63","Queen's Gambit Declined, Orthodox Defense");
mapa.put("D64","Queen's Gambit Declined, Orthodox, Rubinstein Attack");
mapa.put("D65","Queen's Gambit Declined, Orthodox, Rubinstein Attack, Main line");
mapa.put("D66","Queen's Gambit Declined, Orthodox Defense, Bd3 line");
mapa.put("D67","Queen's Gambit Declined, Orthodox Defense, Bd3 line");
mapa.put("D68","Queen's Gambit Declined, Orthodox Defense, Classical");
mapa.put("D69","Queen's Gambit Declined, Orthodox Defense, Classical, 13.de");
mapa.put("D70","Neo-Grunfeld Defense");
mapa.put("D71","Neo-Grunfeld");
mapa.put("D72","Neo-Grunfeld, 5.cd, Main line");
mapa.put("D73","Neo-Grunfeld, 5.Nf3");
mapa.put("D74","Neo-Grunfeld, 6.cd Nxd5, 7.O-O");
mapa.put("D75","Neo-Grunfeld, 6.cd Nxd5, 7.O-O c5, 8.dxc5");
mapa.put("D76","Neo-Grunfeld, 6.cd Nxd5, 7.O-O Nb6");
mapa.put("D77","Neo-Grunfeld, 6.O-O");
mapa.put("D78","Neo-Grunfeld, 6.O-O c6");
mapa.put("D79","Neo-Grunfeld, 6.O-O, Main line");
mapa.put("D80","Grunfeld");
mapa.put("D81","Grunfeld, Russian Variation");
mapa.put("D82","Grunfeld, 4.Bf4");
mapa.put("D83","Grunfeld, Grunfeld Gambit");
mapa.put("D84","Grunfeld, Grunfeld Gambit Accepted");
mapa.put("D85","Grunfeld");
mapa.put("D86","Grunfeld, Exchange");
mapa.put("D87","Grunfeld, Exchange");
mapa.put("D88","Grunfeld, Spassky Variation, Main line, 10...cd, 11.cd");
mapa.put("D89","Grunfeld");
mapa.put("D90","Grunfeld");
mapa.put("D91","Grunfeld, 5.Bg5");
mapa.put("D92","Grunfeld, 5.Bf4");
mapa.put("D93","Grunfeld, with Bf4 & e3");
mapa.put("D94","Grunfeld");
mapa.put("D95","Grunfeld");
mapa.put("D96","Grunfeld, Russian Variation");
mapa.put("D97","Grunfeld, Russian");
mapa.put("D98","Grunfeld, Russian");
mapa.put("D99","Grunfeld Defense, Smyslov");
mapa.put("E00","Queen's Pawn Game");
mapa.put("E01","Catalan, Closed");
mapa.put("E02","Catalan, Open, 5.Qa4");
mapa.put("E03","Catalan, Open");
mapa.put("E04","Catalan, Open, 5.Nf3");
mapa.put("E05","Catalan, Open, Classical line");
mapa.put("E06","Catalan, Closed, 5.Nf3");
mapa.put("E07","Catalan, Closed");
mapa.put("E08","Catalan, Closed");
mapa.put("E09","Catalan, Closed");
mapa.put("E10","Queen's Pawn Game");
mapa.put("E11","Bogo-Indian Defense");
mapa.put("E12","Queen's Indian");
mapa.put("E13","Queen's Indian, 4.Nc3, Main line");
mapa.put("E14","Queen's Indian");
mapa.put("E15","Queen's Indian");
mapa.put("E16","Queen's Indian");
mapa.put("E17","Queen's Indian");
mapa.put("E18","Queen's Indian, Old Main line, 7.Nc3");
mapa.put("E19","Queen's Indian, Old Main line, 9.Qxc3");
mapa.put("E20","Nimzo-Indian");
mapa.put("E21","Nimzo-Indian, Three Knights");
mapa.put("E22","Nimzo-Indian, Spielmann Variation");
mapa.put("E23","Nimzo-Indian, Spielmann");
mapa.put("E24","Nimzo-Indian, Samisch");
mapa.put("E25","Nimzo-Indian, Samisch");
mapa.put("E26","Nimzo-Indian, Samisch");
mapa.put("E27","Nimzo-Indian, Samisch Variation");
mapa.put("E28","Nimzo-Indian, Samisch Variation");
mapa.put("E29","Nimzo-Indian, Samisch");
mapa.put("E30","Nimzo-Indian, Leningrad");
mapa.put("E31","Nimzo-Indian, Leningrad, Main line");
mapa.put("E32","Nimzo-Indian, Classical");
mapa.put("E33","Nimzo-Indian, Classical");
mapa.put("E34","Nimzo-Indian, Classical, Noa Variation");
mapa.put("E35","Nimzo-Indian, Classical, Noa Variation, 5.cd ed");
mapa.put("E36","Nimzo-Indian, Classical");
mapa.put("E37","Nimzo-Indian, Classical");
mapa.put("E38","Nimzo-Indian, Classical, 4...c5");
mapa.put("E39","Nimzo-Indian, Classical, Pirc Variation");
mapa.put("E40","Nimzo-Indian, 4.e3");
mapa.put("E41","Nimzo-Indian");
mapa.put("E42","Nimzo-Indian, 4.e3 c5, 5.Ne2 (Rubinstein)");
mapa.put("E43","Nimzo-Indian, Fischer Variation");
mapa.put("E44","Nimzo-Indian, Fischer Variation, 5.Ne2");
mapa.put("E45","Nimzo-Indian, 4.e3, Bronstein (Byrne) Variation");
mapa.put("E46","Nimzo-Indian");
mapa.put("E47","Nimzo-Indian, 4.e3 O-O 5.Bd3");
mapa.put("E48","Nimzo-Indian, 4.e3 O-O 5.Bd3 d5");
mapa.put("E49","Nimzo-Indian, 4.e3, Botvinnik System");
mapa.put("E50","Nimzo-Indian, 4.e3 O-O 5.Nf3, without ...d5");
mapa.put("E51","Nimzo-Indian, 4.e3");
mapa.put("E52","Nimzo-Indian, 4.e3, Main line with ...b6");
mapa.put("E53","Nimzo-Indian, 4.e3");
mapa.put("E54","Nimzo-Indian, 4.e3, Gligoric System");
mapa.put("E55","Nimzo-Indian, 4.e3, Gligoric System, Bronstein Variation");
mapa.put("E56","Nimzo-Indian, 4.e3, Main line with 7...Nc6");
mapa.put("E57","Nimzo-Indian, 4.e3, Main line with 8...dc and 9...cd");
mapa.put("E58","Nimzo-Indian, 4.e3, Main line with 8...Bxc3");
mapa.put("E59","Nimzo-Indian, 4.e3, Main line");
mapa.put("E60","King's Indian Defense");
mapa.put("E61","King's Indian");
mapa.put("E62","King's Indian, Fianchetto");
mapa.put("E63","King's Indian, Fianchetto, Panno Variation");
mapa.put("E64","King's Indian, Fianchetto, Yugoslav System");
mapa.put("E65","King's Indian, Fianchetto, Yugoslav, 7.O-O");
mapa.put("E66","King's Indian, Fianchetto, Yugoslav Panno");
mapa.put("E67","King's Indian, Fianchetto");
mapa.put("E68","King's Indian, Fianchetto, Classical Variation, 8.e4");
mapa.put("E69","King's Indian, Fianchetto, Classical Main line");
mapa.put("E70","King's Indian");
mapa.put("E71","King's Indian, Makagonov System (5.h3)");
mapa.put("E72","King's Indian");
mapa.put("E73","King's Indian");
mapa.put("E74","King's Indian, Averbakh, 6...c5");
mapa.put("E75","King's Indian, Averbakh, Main line");
mapa.put("E76","King's Indian, Four Pawns Attack");
mapa.put("E77","King's Indian");
mapa.put("E78","King's Indian, Four Pawns Attack, with Be2 and Nf3");
mapa.put("E79","King's Indian, Four Pawns Attack, Main line");
mapa.put("E80","King's Indian, Samisch Variation");
mapa.put("E81","King's Indian, Samisch");
mapa.put("E82","King's Indian, Samisch, double Fianchetto Variation");
mapa.put("E83","King's Indian, Samisch");
mapa.put("E84","King's Indian, Samisch, Panno Main line");
mapa.put("E85","King's Indian, Samisch, Orthodox Variation");
mapa.put("E86","King's Indian, Samisch, Orthodox, 7.Nge2 c6");
mapa.put("E87","King's Indian, Samisch, Orthodox");
mapa.put("E88","King's Indian, Samisch, Orthodox, 7.d5 c6");
mapa.put("E89","King's Indian, Samisch, Orthodox Main line");
mapa.put("E90","King's Indian");
mapa.put("E91","King's Indian");
mapa.put("E92","King's Indian");
mapa.put("E93","King's Indian, Petrosian System");
mapa.put("E94","King's Indian, Orthodox");
mapa.put("E95","King's Indian, Orthodox, 7...Nbd7, 8.Re1");
mapa.put("E96","King's Indian, Orthodox, 7...Nbd7, Main line");
mapa.put("E97","King's Indian");
mapa.put("E98","King's Indian, Orthodox, Taimanov, 9.Ne1");
mapa.put("E99","King's Indian, Orthodox, Taimanov");
        
        return mapa;
        
    }
    
    
}
